#配置当前服务的端口号
server:
  port: 9001
spring:
  #配置当前服务在注册中心的名称
  application:
    name: student-service
  #配置Mysql的相关信息
  datasource:
    url: jdbc:mysql://localhost:3306/jizheping?characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #配置数据源相关信息,当前使用的数据源为alibaba的Druid
    druid:
      initial-size: 1 #初始化连接数
      min-idle: 1  #最小空闲连接
      max-active: 1 #最大活动连接
      test-on-borrow: true #获取连接时测试是否可用
      stat-view-servlet.allow: true
  main:
    allow-bean-definition-overriding: true
#配置Mybatis的相关信息
mybatis:
  #配置Mybatis中实体的位置,用户Mapper.xml中使用别名
  type-aliases-package: com.jizheping.entity
  #配置Mybatis中Mapper.xml的位置
  mapper-locations: classpath:mapper/*Mapper.xml
#配置Eureka注册的地址,用于服务向当前服务进行注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/